Repository bgoonz/BGOONZ_BLOG_2.0, pull requests merged in 2022-05, with the labels that each got.

#2074 Create BlogTags “ukraine”
  src/data/tags/ukraine.yaml
Labels: netlify-cms/pending_publish

#2078 Update BlogTags “ukraine”
  src/data/tags/ukraine.yaml
Labels: netlify-cms/pending_publish

#2079 Create BlogCategories “js”
  src/data/categories/js.yaml
Labels: netlify-cms/pending_publish

#2080 Create BlogAuthors “bgoonz”
  src/data/authors/bgoonz.yaml
Labels: netlify-cms/pending_publish

#2081 Create Blog “react-state”
  src/pages/blog/react-state.md
  static/images/uploads/blog/particle-collision.jpg
  static/images/uploads/blog/react2.jpg
Labels: netlify-cms/pending_publish

#2112 Create BlogAuthors “backup”
  src/data/authors/backup.yaml
  static/images/uploads/blog/code.png
Labels: netlify-cms/pending_publish

#2113 Create Docs “tips/top-10-money-tips/index”
  src/pages/docs/tips/top-10-money-tips/index.md
Labels: netlify-cms/pending_publish

#2120 Create Docs “projects/links/index”
  src/pages/docs/projects/links/index.md
Labels: netlify-cms/pending_publish

#2135 Create Blog “webdev-setup”
  src/pages/blog/webdev-setup.md
Labels: netlify-cms/pending_publish

#2138 Create Blog “10-essential-react-interview-questions”
  src/pages/blog/10-essential-react-interview-questions.md
  static/images/uploads/blog/react.jpg
Labels: netlify-cms/pending_publish

#2141 Create BlogTags “tools”
  src/data/tags/tools.yaml
Labels: netlify-cms/pending_publish

#2156 Create Blog “beginners-guide-to-python”
  src/pages/blog/beginners-guide-to-python.md
  static/images/uploads/blog/python-language.jpg
Labels: netlify-cms/pending_publish

#2157 Create BlogCategories “python”
  src/data/categories/python.yaml
Labels: netlify-cms/pending_publish

#2164 Update Blog “5-tips-for-better-pull-requests”
  src/pages/blog/5-tips-for-better-pull-requests.md
  static/images/uploads/blog/pull-request.jpg
Labels: netlify-cms/pending_publish

#2158 Create BlogCategories “gatsbyjs”
  src/data/categories/gatsbyjs.yaml
Labels: netlify-cms/pending_publish

#2162 Create Blog “gatsby-cli”
  src/pages/blog/gatsby-cli.md
Labels: netlify-cms/draft

#2165 Update Blog “10-essential-react-interview-questions”
  src/pages/blog/10-essential-react-interview-questions.md
  static/images/uploads/blog/react.png
Labels: netlify-cms/draft

#2160 Create BlogTags “career”
  src/data/tags/career.yaml
Labels: netlify-cms/draft

#2167 Update Blog “10-essential-react-interview-questions”
  static/images/uploads/blog/sequelize.png
Labels: netlify-cms/pending_publish

#2170 Create Blog “file-system-route-api”
  src/pages/blog/file-system-route-api.md
  static/images/uploads/blog/gatsby.png
Labels: netlify-cms/draft

#2174 Create Docs “python/data-structures-in-python/index”
  src/pages/docs/python/data-structures-in-python/index.md
Labels: netlify-cms/pending_publish

#2168 Update Blog “data-structures-algorithms-resources”
  src/pages/blog/data-structures-algorithms-resources.md
  static/images/uploads/blog/big-o-chart.png
Labels: netlify-cms/pending_publish

#2176 Create BlogCategories “google”
  src/data/categories/google.yaml
Labels: netlify-cms/pending_publish

#2179 Update Blog “psql-cheat-sheet”
  src/pages/blog/psql-cheat-sheet.md
Labels: netlify-cms/pending_publish

#2177 Update Blog “beginners-guide-to-python”
  src/pages/blog/beginners-guide-to-python.md
Labels: netlify-cms/pending_publish

#2181 Create Blog “deploy-react-app-to-heroku”
  src/pages/blog/deploy-react-app-to-heroku.md
Labels: netlify-cms/pending_publish

#2183 Create Docs “overflow/emmet-cheat-sheet/index”
  src/pages/docs/overflow/emmet-cheat-sheet/index.md
Labels: netlify-cms/pending_publish

#2186 Update Blog “psql-cheat-sheet”
  src/pages/blog/psql-cheat-sheet.md
  static/images/uploads/blog/psql-diagram.jpg
Labels: netlify-cms/pending_publish

#2187 Update Blog “vs-code-extensions”
  src/pages/blog/vs-code-extensions.md
  static/images/uploads/blog/vscode-extensions-list.png
Labels: netlify-cms/pending_publish

#2188 Update Blog “using-the-dom”
  src/pages/blog/using-the-dom.md
  static/images/uploads/blog/using-the-dom.png
Labels: netlify-cms/pending_publish

#2190 Update Blog “react-semantics”
  src/pages/blog/react-semantics.md
Labels: netlify-cms/pending_publish

#2191 Update Blog “react-semantics”
  src/pages/blog/react-semantics.md
Labels: netlify-cms/pending_publish

#2192 Create Docs “tips/decrement/index”
  src/pages/docs/tips/decrement/index.md
Labels: netlify-cms/pending_publish

#2193 Update Docs “git/index”
  src/pages/docs/git/git/git-cheatsheet.md
  src/pages/docs/git/git/github-tutorial/index.md
  src/pages/docs/git/git/index.md
  src/pages/docs/git/index.md
Labels: netlify-cms/pending_publish

#2195 Update Docs “about/resume”
  src/pages/docs/career/about/eng-portfolio.md
  src/pages/docs/career/about/index.md
  src/pages/docs/career/about/internal-use.md
  src/pages/docs/career/about/intrests.md
  src/pages/docs/career/about/job-search.md
  src/pages/docs/career/about/readme.md
  src/pages/docs/career/about/resume.md
Labels: netlify-cms/pending_publish

#2197 Update Docs “about/resume”
  src/pages/docs/about/index.md
Labels: netlify-cms/draft

#2202 Create Blog “intro-to-markdown”
  src/pages/blog/intro-to-markdown.md
  static/images/markdown.png
Labels: netlify-cms/pending_publish

#2203 Update Blog “deploy-react-app-to-heroku”
  src/pages/blog/deploy-react-app-to-heroku.md
  static/images/heroku.png
  static/images/pull-request.jpg
  static/images/using-the-dom.png
Labels: netlify-cms/pending_publish

#2204 Update Blog “intro-01-data-structures”
  src/pages/blog/intro-01-data-structures.md
  static/images/ds-algo.png
Labels: netlify-cms/pending_publish

#2205 Update Blog “react-state”
  src/pages/blog/react-state.md
Labels: netlify-cms/pending_publish

#2206 Update Blog “psql-cheat-sheet”
  src/pages/blog/psql-cheat-sheet.md
  static/images/psql-diagram.jpg
Labels: netlify-cms/pending_publish

#2207 Update Blog “data-structures-algorithms-resources”
  src/pages/blog/data-structures-algorithms-resources.md
Labels: netlify-cms/pending_publish

#2208 Update Blog “vs-code-extensions”
  src/pages/blog/vs-code-extensions.md
Labels: netlify-cms/pending_publish

#2209 Update Blog “passing-arguments-to-a-callback-in-js”
  src/pages/blog/passing-arguments-to-a-callback-in-js.md
Labels: netlify-cms/pending_publish

#2210 Update Blog “beginners-guide-to-python”
  src/pages/blog/beginners-guide-to-python.md
Labels: netlify-cms/pending_publish

#2212 Update Blog “file-system-route-api”
  src/pages/blog/file-system-route-api.md
  static/images/file-system.jpg
Labels: netlify-cms/pending_publish

#2217 Create BlogCategories “react-1”
  src/data/categories/react-1.yaml
Labels: netlify-cms/pending_publish

#2218 Create BlogCategories “ds-algo”
  src/data/categories/ds-algo.yaml
Labels: netlify-cms/pending_publish

#2219 Create BlogCategories “resources”
  src/data/categories/resources.yaml
Labels: netlify-cms/draft

#2222 Create Blog “what-is-a-redux-reducer”
  src/pages/blog/what-is-a-redux-reducer.md
  static/images/redux.gif
Labels: netlify-cms/pending_publish

#2225 Create Blog “google-analytics”
  src/pages/blog/google-analytics.md
  static/images/uploads/blog/analytics.jpg
Labels: netlify-cms/pending_publish

#2227 Create BlogCategories “javascript”
  src/data/categories/javascript.yaml
Labels: netlify-cms/pending_publish

#2228 Create BlogTags “python”
  src/data/tags/python.yaml
Labels: netlify-cms/draft

#2235 Update Blog “intro-to-markdown”
  src/pages/blog/intro-to-markdown.md
Labels: netlify-cms/pending_publish

#2236 Update Blog “data-structures-algorithms-resources”
  src/pages/blog/data-structures-algorithms-resources.md
Labels: netlify-cms/pending_publish

#2237 Update Blog “beginners-guide-to-python”
  src/pages/blog/beginners-guide-to-python.md
Labels: netlify-cms/pending_publish

#2238 Update Blog “5-tips-for-better-pull-requests”
  src/pages/blog/5-tips-for-better-pull-requests.md
Labels: netlify-cms/pending_publish

#2242 Create Blog “useful-stock-images”
  src/pages/blog/useful-stock-images.md
  static/images/uploads/blog/analytics.jpg
  static/images/uploads/blog/bassist.gif
  static/images/uploads/blog/code.png
  static/images/uploads/blog/gradients_3.png
  static/images/uploads/blog/nasa_earth_grid.jpg
  static/images/uploads/blog/nasa_new_york_city_grid.jpg
  static/images/uploads/blog/nasa_space_shuttle_challenger.jpg
  static/images/uploads/blog/nasa_the_blue_marble-1-.jpg
  static/images/uploads/blog/woodcuts_1.jpg
Labels: netlify-cms/pending_publish

#2254 Update Blog “data-structures-algorithms-resources”
  src/pages/blog/data-structures-algorithms-resources.md
Labels: netlify-cms/pending_publish

#2257 Create BlogTags “resources”
  src/data/tags/resources.yaml
Labels: netlify-cms/pending_publish

#2256 Create BlogCategories “awesome-lists”
  src/data/categories/awesome-lists.yaml
Labels: netlify-cms/draft

#2258 Create BlogTags “react”
  src/data/tags/react.yaml
Labels: netlify-cms/draft

#2260 Create BlogTags “javascript”
  src/data/tags/javascript.yaml
Labels: netlify-cms/draft

#2262 Create Docs “javascript/asynchronous-javascript-and-xml/index”
  src/pages/docs/javascript/asynchronous-javascript-and-xml/index.md
Labels: netlify-cms/pending_publish

#2263 Create Docs “react/higher-order-components/index”
  src/pages/docs/react/higher-order-components/index.md
Labels: netlify-cms/pending_publish

#2265 Update Blog “10-essential-react-interview-questions”
  src/pages/blog/10-essential-react-interview-questions.md
Labels: netlify-cms/pending_publish

#2270 Update Blog “file-system-route-api”
  src/pages/blog/file-system-route-api.md
Labels: netlify-cms/pending_publish

#2268 Update Blog “embedding-media-in-html”
  src/pages/blog/embedding-media-in-html.md
Labels: netlify-cms/draft

#2266 Update Blog “5-tips-for-better-pull-requests”
  src/pages/blog/5-tips-for-better-pull-requests.md
Labels: netlify-cms/draft

#2274 Update Blog “deploy-react-app-to-heroku”
  src/pages/blog/deploy-react-app-to-heroku.md
Labels: netlify-cms/draft

#2271 Update Blog “google-analytics”
  src/pages/blog/google-analytics.md
Labels: netlify-cms/draft

#2278 Create Docs “tips/httrack/index”
  src/pages/docs/tips/httrack/index.md
Labels: netlify-cms/pending_publish

#2276 Update Blog “10-essential-react-interview-questions”
  src/pages/blog/10-essential-react-interview-questions.md
Labels: netlify-cms/draft

#2280 Create Docs “css/css-selector-specificity/index”
  src/pages/docs/css/css-selector-specificity/index.md
Labels: netlify-cms/pending_publish

#2281 Create Docs “css/the-box-model/index”
  src/pages/docs/css/the-box-model/index.md
Labels: netlify-cms/pending_publish

#2283 Create BlogTags “data-structures-algorithms”
  src/data/tags/data-structures-algorithms.yaml
Labels: netlify-cms/draft

#2282 Create BlogTags “career-1”
  src/data/tags/career-1.yaml
Labels: netlify-cms/draft

#2292 Create Blog “python-quiz”
  src/pages/blog/python-quiz.md
Labels: netlify-cms/pending_publish

#2296 Create Docs “fetch-api/index”
  src/pages/docs/fetch-api/index.md
Labels: netlify-cms/pending_publish

#2291 Create Blog “eslint-rules”
  src/pages/blog/eslint-rules.md
Labels: netlify-cms/pending_publish

#2297 Update Blog “10-essential-react-interview-questions”
  static/images/uploads/blog/react.jpg
Labels: netlify-cms/draft

#2306 Update Blog “embedding-media-in-html”
  src/pages/blog/embedding-media-in-html.md
  static/images/uploads/blog/embedded-media.png
Labels: netlify-cms/pending_publish

#2307 Update Blog “google-analytics”
  src/pages/blog/google-analytics.md
  static/images/uploads/blog/google-analytics.jpg
Labels: netlify-cms/draft

#2303 Update Blog “10-essential-react-interview-questions”
  src/pages/blog/10-essential-react-interview-questions.md
Labels: netlify-cms/draft

#2309 Create Blog “front-end-interview-questions-part-2”
  src/pages/blog/front-end-interview-questions-part-2.md
Labels: netlify-cms/pending_publish

#2311 Update Blog “python-quiz”
  src/pages/blog/python-quiz.md
  static/images/uploads/blog/python.png
Labels: netlify-cms/pending_publish

#2312 Update Blog “google-analytics”
  src/pages/blog/google-analytics.md
  static/images/uploads/blog/analytics.jpg
Labels: netlify-cms/pending_publish

#2319 Create BlogCategories “webdevhub”
  src/data/categories/webdevhub.yaml
Labels: netlify-cms/pending_publish

#2320 Update Blog “embedding-media-in-html”
  src/pages/blog/embedding-media-in-html.md
Labels: netlify-cms/pending_publish

#2321 Update Blog “deploy-react-app-to-heroku”
  src/pages/blog/deploy-react-app-to-heroku.md
  static/images/uploads/blog/heroku.png
Labels: netlify-cms/pending_publish

#2322 Update Blog “google-analytics”
  src/pages/blog/google-analytics.md
Labels: netlify-cms/pending_publish

#2324 Update Blog “passing-arguments-to-a-callback-in-js”
  src/pages/blog/passing-arguments-to-a-callback-in-js.md
  static/images/uploads/blog/call-stack-second-example.png
Labels: netlify-cms/pending_publish

#2327 Update Blog “useful-stock-images”
  src/pages/blog/useful-stock-images.md
Labels: netlify-cms/pending_publish

#2328 Update Blog “10-essential-react-interview-questions”
  src/pages/blog/10-essential-react-interview-questions.md
Labels: netlify-cms/pending_publish

#2329 Update Blog “react-semantics”
  src/pages/blog/react-semantics.md
Labels: netlify-cms/pending_publish

#2330 Update Blog “react-state”
  src/pages/blog/react-state.md
Labels: netlify-cms/pending_publish

#2331 Update Blog “using-the-dom”
  src/pages/blog/using-the-dom.md
Labels: netlify-cms/pending_publish

#2332 Update Blog “vs-code-extensions”
  src/pages/blog/vs-code-extensions.md
Labels: netlify-cms/pending_publish

#2334 Update Blog “htt-requests”
  src/pages/blog/htt-requests.md
Labels: netlify-cms/pending_publish

#2335 Update Blog “adding-css-to-your-html”
  static/images/uploads/blog/css.webp
Labels: netlify-cms/pending_publish

#2338 Create BlogCategories “content-management”
  src/data/categories/content-management.yaml
Labels: netlify-cms/pending_publish

#2340 Create Docs “tips/firebase-hosting/index”
  src/pages/docs/tips/firebase-hosting/index.md
Labels: netlify-cms/pending_publish

#2344 Create Docs “content/javascript-examples/index”
  src/pages/docs/content/javascript-examples/index.md
Labels: netlify-cms/pending_publish

#2345 Create BlogTags “databases”
  src/data/tags/databases.yaml
Labels: netlify-cms/pending_publish

#2348 Create Blog “react-fragments”
  src/pages/blog/react-fragments.md
Labels: netlify-cms/pending_publish

#2349 Create Blog “jsx-in-depth”
  src/pages/blog/jsx-in-depth.md
Labels: netlify-cms/pending_publish

#2350 Update Blog “beginners-guide-to-python”
  src/pages/blog/beginners-guide-to-python.md
Labels: netlify-cms/pending_publish

#2351 Update Blog “deploy-react-app-to-heroku”
  src/pages/blog/deploy-react-app-to-heroku.md
Labels: netlify-cms/pending_publish

#2353 Update Blog “embedding-media-in-html”
  src/pages/blog/embedding-media-in-html.md
Labels: netlify-cms/pending_publish

#2354 Update Blog “data-structures-algorithms-resources”
  src/pages/blog/data-structures-algorithms-resources.md
Labels: netlify-cms/pending_publish

#2355 Update Blog “event-handeling”
  src/pages/blog/event-handeling.md
Labels: netlify-cms/pending_publish

#2356 Update Blog “file-system-route-api”
  src/pages/blog/file-system-route-api.md
Labels: netlify-cms/pending_publish

#2369 Update Blog “gatsby-cli”
  src/pages/blog/gatsby-cli.md
Labels: netlify-cms/pending_publish

#2371 Update Blog “google-analytics”
  src/pages/blog/google-analytics.md
Labels: netlify-cms/pending_publish

#2372 Update Blog “grep-in-linuz”
  src/pages/blog/grep-in-linuz.md
Labels: netlify-cms/pending_publish

#2373 Update Blog “intro-01-data-structures”
  src/pages/blog/intro-01-data-structures.md
Labels: netlify-cms/pending_publish

#2374 Update Blog “intro-to-markdown”
  src/pages/blog/intro-to-markdown.md
Labels: netlify-cms/pending_publish

#2381 Create Blog “code-playgrounds-of-2021”
  src/pages/blog/code-playgrounds-of-2021.md
Labels: netlify-cms/pending_publish

#2385 Update Blog “vscode-extensions”
  src/pages/blog/vscode-extensions.md
Labels: netlify-cms/pending_publish

#2383 Update Blog “data-structures-algorithms-resources”
  src/pages/blog/data-structures-algorithms-resources.md
Labels: netlify-cms/pending_publish

#2388 Create BlogTags “search”
  src/data/tags/search.yaml
Labels: netlify-cms/pending_publish

#2389 Update Blog “useful-stock-images”
  src/pages/blog/useful-stock-images.md
Labels: netlify-cms/pending_publish

#2391 Create Blog “wordpress-vs-headless-cms”
  src/pages/blog/wordpress-vs-headless-cms.md
Labels: netlify-cms/pending_publish

#2392 Create Docs “javascript/javascript-resource-table/index”
  src/pages/docs/javascript/javascript-resource-table/index.md
Labels: netlify-cms/draft

#2394 Update Blog “what-is-a-redux-reducer”
  src/pages/blog/what-is-a-redux-reducer.md
Labels: netlify-cms/pending_publish

#2400 Update Blog “python-quiz”
  src/pages/blog/python-quiz.md
Labels: netlify-cms/pending_publish

#2398 Create Docs “react/react-study-guide/index”
  src/pages/docs/react/react-study-guide/index.md
Labels: netlify-cms/pending_review

#2401 Update Blog “psql-cheat-sheet”
  src/pages/blog/psql-cheat-sheet.md
Labels: netlify-cms/pending_publish

#2405 Update Blog “passing-arguments-to-a-callback-in-js”
  src/pages/blog/passing-arguments-to-a-callback-in-js.md
Labels: netlify-cms/pending_publish

#2411 Update Blog “webdev-setup”
  src/pages/blog/webdev-setup.md
Labels: netlify-cms/pending_publish

#2426 Create Docs “overflow/https/index”
  src/pages/docs/overflow/https/index.md
Labels: netlify-cms/pending_publish

#2430 Create Blog “awesome-resources”
  src/pages/blog/awesome-resources.md
Labels: netlify-cms/pending_publish

#2431 Update Blog “awesome-resources”
  src/pages/blog/awesome-resources.md
Labels: netlify-cms/pending_publish

#2433 Update BlogAuthors “backup”
  src/data/authors/backup.yaml
Labels: netlify-cms/pending_publish

#2439 Update BlogAuthors “bgoonz”
  src/data/authors/bgoonz.yaml
Labels: netlify-cms/pending_publish

#2440 Update BlogAuthors “backup”
  src/data/authors/backup.yaml
Labels: netlify-cms/pending_publish

#2441 Update BlogAuthors “backup”
  src/data/authors/backup.yaml
  static/images/uploads/blog/wartime-blog-cover-art-modified.png
Labels: netlify-cms/pending_publish

#2442 Create Blog “accessibility”
  src/pages/blog/accessibility.md
Labels: netlify-cms/pending_publish

#2445 Create Blog “fast-refresh”
  src/pages/blog/fast-refresh.md
Labels: netlify-cms/pending_publish

#2447 Create Blog “web-dev-frameworks”
  src/pages/blog/web-dev-frameworks.md
Labels: netlify-cms/pending_publish

#2448 Create BlogTags “aria”
  src/data/tags/aria.yaml
Labels: netlify-cms/pending_publish

#2449 Create BlogTags “array”
  src/data/tags/array.yaml
Labels: netlify-cms/pending_publish

#2450 Create Docs “python/python-modules/index”
  src/pages/docs/python/python-modules/index.md
Labels: netlify-cms/pending_publish
